### ISSUE TITLE
wrong encoding of SVG files

### ISSUE THREAD

**Issue by torstenwerner** [schoeffm/waggly-uml#1]
Hi,

I have converted the attached file on OS X with
    wuml -i seq.wuml -f svg -t sequence -o seq.svg
The SVG has an XML header with encoding="ISO-8859-1" but contains UTF-8 characters e.g. «create». That causes display errors in chrome.

Regards,
Torsten

[seq.zip](https://github.com/schoeffm/waggly-uml/files/156450/seq.zip)

**Comment by schoeffm** [comment]
I've added a (naive) [post-processing-step](https://github.com/schoeffm/waggly-uml/commit/c3a7a092a7d22d41f84532e9845a35435868e561) which places a UTF-8 encoding into the header. This should fix at least your issue. A better solution would be if the underlying tool (pic2plot in this case) would directly support the specification of the encoding to be used - but this is not the case as it seems.
So, update to the new version >= [0.2.1](https://www.npmjs.com/package/wuml) and your problem should be fixed
